apiVersion: v1
kind: Service
metadata:
  name: gemma3
  namespace: rhaiis
  labels:
    app: gemma3
spec:
  selector:
    app: gemma3
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP